"""empty message

Revision ID: 77a339705b88
Revises: e195feaf370b
Create Date: 2022-02-02 20:38:42.423750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a339705b88'
down_revision = 'e195feaf370b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'car', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_column('car', 'customer_id')
    # ### end Alembic commands ###
